[project]
name = "newsbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=1.8.0",
    "feedparser>=6.0.14",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
]

[project.scripts]
newsbot = "newsbot:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
